spring.application.name=lista-de-tarefas
spring.datasource.url=jdbc:postgresql://localhost:5432/Seu_Banco
spring.datasource.username=usuario_aqui
spring.datasource.password=senha_aqui
spring.datasource.driver-class-name=org.postgresql.Driver